	
@startuml
skinparam actorStyle Hollow
left to right direction
actor Client as c
package Professional {
  actor Admin as a
  actor "Translator" as tr
}
package EasyTanslate {
  usecase "Log in" as UC1
  usecase "Add a task" as UC2
  usecase "Add a task review" as UC3
  usecase "View all English Translators" as UC4
  usecase "View my tasks" as UC5
  usecase "Register a client" as UC6
  usecase "Register a translator" as UC7
  usecase "Confirm a task" as UC8
}
c --> UC4
c --> UC1
tr --> UC1
c --> UC2
c --> UC5
tr --> UC5
a --> UC6
a --> UC7
a --> UC8
tr --> UC8
c --> UC3

@enduml